name: arabic_roman_conv
description: a flexible, easy-to-use Flutter package that provides tools for the conversion of Arabic names and phrases to their Romanized (English) counterparts.
repository: https://github.com/1saifj/arabic_roman_conv
version: 0.1.0-dev.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  very_good_analysis: ">=5.0.0 <8.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - romanization
  - localization
